# Generated by Django 5.0.6 on 2024-07-11 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_initial'),
        ('core', '0001_initial'),
        ('creditcards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='db',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.db'),
        ),
        migrations.AddField(
            model_name='creditcardinstallment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditcardinstallment',
            name='db',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.db'),
        ),
        migrations.AddField(
            model_name='creditcardtransaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
        migrations.AddField(
            model_name='creditcardtransaction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditcardtransaction',
            name='creditcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='creditcards.creditcard'),
        ),
        migrations.AddField(
            model_name='creditcardtransaction',
            name='db',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.db'),
        ),
        migrations.AddField(
            model_name='creditcardtransaction',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.subcategory'),
        ),
        migrations.AddField(
            model_name='creditcardinstallment',
            name='creditcard_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_installments', to='creditcards.creditcardtransaction'),
        ),
        migrations.AlterUniqueTogether(
            name='creditcard',
            unique_together={('name', 'account')},
        ),
    ]
