# Generated by Django 5.0.6 on 2024-07-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LogSystem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exception', models.CharField(max_length=255)),
                ('request', models.TextField()),
                ('traceback', models.TextField(null=True)),
                ('data', models.TextField(null=True)),
            ],
        ),
    ]
